leftnav:
- identifier: 76f8e098-877f-4c20-91ee-237ebf04a428
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 311b8a27-7162-417d-8ab0-db1ce379098f
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 20
- identifier: d56984d2-7e01-4ab8-996f-5b9c1bc06672
  name: Supplementary notes
  url: /pages/supplementary-notes
  weight: 30
